const products = [
  {
    id: 1,
    name: "Olma",
    category: "Meva",
    description: "Qizil, yashil yoki sariq rangdagi dumaloq meva",
    price: 89,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/1.png",
      "../assets/images/products/2.png",
      "../assets/images/products/3.png",
      "../assets/images/products/4.png",
    ],
  },
  {
    id: 2,
    name: "Banan",
    category: "Meva",
    description: "Sariq po'stli, uzun, egri shakldagi shirin meva",
    price: 71,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/2.png",
      "../assets/images/products/3.png",
      "../assets/images/products/4.png",
      "../assets/images/products/5.png",
    ],
  },
  {
    id: 3,
    name: "Non",
    category: "Nonvoyxona",
    description: "Un, suv va xamirturushdan tayyorlangan asosiy oziq-ovqat",
    price: 88,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/3.png",
      "../assets/images/products/4.png",
      "../assets/images/products/5.png",
      "../assets/images/products/6.png",
    ],
  },
  {
    id: 4,
    name: "Brokoli",
    category: "Sabzavot",
    description: "Yuqori ozuqa moddalariga ega bo'lgan yashil daraxtsimon sabzavot",
    price: 94,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/4.png",
      "../assets/images/products/5.png",
      "../assets/images/products/6.png",
      "../assets/images/products/7.png",
    ],
  },
  {
    id: 5,
    name: "Sabzi",
    category: "Sabzavot",
    description: "Qirrali tuzilishga va shirin, yeryong'oq hushbo'ylikka ega ildiz sabzavoti",
    price: 82,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/5.png",
      "../assets/images/products/6.png",
      "../assets/images/products/7.png",
      "../assets/images/products/8.png",
    ],
  },
  {
    id: 6,
    name: "Pishloq",
    category: "Sut mahsulotlari",
    description: "Sutdan tayyorlanadigan turli tuzilish va lazzatdagi mahsulot",
    price: 91,
    rating: 3.5,
    discount: 50,
    images: [
      "../assets/images/products/6.png",
      "../assets/images/products/7.png",
      "../assets/images/products/8.png",
      "../assets/images/products/9.png",
    ],
  },
  {
    id: 7,
    name: "Tovuq go'shti",
    category: "Go'sht",
    description: "Ovqatlarda oqsil manbai sifatida ishlatiladigan parranda go'shti",
    price: 68,
    rating: 3.5,
    discount: 20,
    images: [
      "../assets/images/products/7.png",
      "../assets/images/products/8.png",
      "../assets/images/products/9.png",
      "../assets/images/products/10.png",
    ],
  },
  {
    id: 8,
    name: "Shokolad",
    category: "Shirinlik",
    description: "Kakao loviyalaridan tayyorlanadigan turli shirinliklar va desertlar",
    price: 61,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/8.png",
      "../assets/images/products/9.png",
      "../assets/images/products/10.png",
      "../assets/images/products/11.png",
    ],
  },
  {
    id: 9,
    name: "Kofe",
    category: "Ichimlik",
    description: "Qovurilgan kofe loviyalaridan tayyorlanadigan achchiq ichimlik",
    price: 98,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/9.png",
      "../assets/images/products/10.png",
      "../assets/images/products/11.png",
      "../assets/images/products/12.png",
    ],
  },
  {
    id: 10,
    name: "Tuxum",
    category: "Sut mahsulotlari",
    description: "Qushlar tomonidan ishlab chiqariladigan oval shakldagi oqsil manbai",
    price: 79,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/10.png",
      "../assets/images/products/11.png",
      "../assets/images/products/12.png",
      "../assets/images/products/13.png",
    ],
  },
  {
    id: 11,
    name: "Baliq",
    category: "Go'sht",
    description: "Omega-3 yog' kislotalari va yuqori oqsil miqdori bilan mashhur dengiz mahsuloti",
    price: 89,
    rating: 3.5,
    discount: 50,
    images: [
      "../assets/images/products/11.png",
      "../assets/images/products/12.png",
      "../assets/images/products/13.png",
      "../assets/images/products/14.png",
    ],
  },
  {
    id: 12,
    name: "Uzum",
    category: "Meva",
    description: "Mayda, shirin mevalar to'plami, ko'pincha vino tayyorlashda ishlatiladi",
    price: 61,
    rating: 4,
    discount: 20,
    images: [
      "../assets/images/products/12.png",
      "../assets/images/products/13.png",
      "../assets/images/products/14.png",
      "../assets/images/products/15.png",
    ],
  },
  {
    id: 13,
    name: "Gamburger",
    category: "Fast food",
    description:
      "Maydalangan mol go'shti kotleti, bulka va turli xil ustunalardan tayyorlangan sendvich",
    price: 87,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/13.png",
      "../assets/images/products/14.png",
      "../assets/images/products/15.png",
      "../assets/images/products/16.png",
    ],
  },
  {
    id: 14,
    name: "Xot-dog",
    category: "Fast food",
    description: "Uzun bulka ichida beriladigan kolbasa turi, tez va qulay ovqat",
    price: 84,
    rating: 4.5,
    discount: 50,
    images: [
      "../assets/images/products/14.png",
      "../assets/images/products/15.png",
      "../assets/images/products/16.png",
      "../assets/images/products/17.png",
    ],
  },
  {
    id: 15,
    name: "Muzqaymoq",
    category: "Shirinlik",
    description:
      "Qaymoq, shakar va lazzat beruvchi moddalardan tayyorlanadigan muzlatilgan shirinlik",
    price: 68,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/15.png",
      "../assets/images/products/16.png",
      "../assets/images/products/17.png",
      "../assets/images/products/18.png",
    ],
  },
  {
    id: 16,
    name: "Limon",
    category: "Meva",
    description: "Sariq sitrus mevasi, nordon ta'mi bilan oshpazlikda keng qo'llaniladi",
    price: 74,
    rating: 3.5,
    discount: 0,
    images: [
      "../assets/images/products/16.png",
      "../assets/images/products/17.png",
      "../assets/images/products/18.png",
      "../assets/images/products/19.png",
    ],
  },
  {
    id: 17,
    name: "Tuxumlar",
    category: "Sut mahsulotlari",
    description:
      "Qushlar va ba'zi sudralib yuruvchilar tomonidan ishlab chiqariladigan oval shakldagi reproduktiv tuzilmalar",
    price: 70,
    rating: 4.5,
    discount: 50,
    images: [
      "../assets/images/products/17.png",
      "../assets/images/products/18.png",
      "../assets/images/products/19.png",
      "../assets/images/products/20.png",
    ],
  },
  {
    id: 18,
    name: "Asal",
    category: "Sut mahsulotlari",
    description: "Ariyalar gul nektaridan tayyorlaydigan shirin, yopishqoq suyuqlik",
    price: 87,
    rating: 4,
    discount: 0,
    images: [
      "../assets/images/products/18.png",
      "../assets/images/products/19.png",
      "../assets/images/products/20.png",
      "../assets/images/products/21.png",
    ],
  },
  {
    id: 19,
    name: "Muzqaymoq",
    category: "Shirinlik",
    description:
      "Qaymoq, shakar va lazzat beruvchi moddalardan tayyorlanadigan muzlatilgan shirinlik",
    price: 83,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/19.png",
      "../assets/images/products/20.png",
      "../assets/images/products/21.png",
      "../assets/images/products/22.png",
    ],
  },
  {
    id: 20,
    name: "Murabbo",
    category: "Meva",
    description:
      "Meva sharbati va shakardan tayyorlanadigan shirinlik, non yoki pechenelarga ustiga surtiladi",
    price: 76,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/20.png",
      "../assets/images/products/21.png",
      "../assets/images/products/22.png",
      "../assets/images/products/23.png",
    ],
  },
  {
    id: 21,
    name: "Ketchup",
    category: "Sous",
    description: "Pomidor, sirka, shakar va ziravorlardan tayyorlanadigan nordon sous",
    price: 77,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/21.png",
      "../assets/images/products/22.png",
      "../assets/images/products/23.png",
      "../assets/images/products/24.png",
    ],
  },
  {
    id: 22,
    name: "Mango",
    category: "Meva",
    description: "Shirin, sharbatli tropik meva, go'shti qalin va markazida yirik urug'i bor",
    price: 80,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/22.png",
      "../assets/images/products/23.png",
      "../assets/images/products/24.png",
      "../assets/images/products/25.png",
    ],
  },
  {
    id: 23,
    name: "Lapsha",
    category: "Makaron",
    description: "Bug'doy unidan tayyorlanadigan makaron turi, Osiyo oshxonasida keng qo'llaniladi",
    price: 93,
    rating: 3.5,
    discount: 20,
    images: [
      "../assets/images/products/23.png",
      "../assets/images/products/24.png",
      "../assets/images/products/25.png",
      "../assets/images/products/26.png",
    ],
  },
  {
    id: 24,
    name: "Javdar yormasi",
    category: "Nonushta",
    description: "Javdar donlaridan tayyorlanadigan kasha, ko'pincha nonushtada iste'mol qilinadi",
    price: 94,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/24.png",
      "../assets/images/products/25.png",
      "../assets/images/products/26.png",
      "../assets/images/products/27.png",
    ],
  },
  {
    id: 25,
    name: "Bekon",
    category: "Nonushta",
    description: "Tuzlangan cho'chqa go'shtidan tayyorlanadigan mashhur nonushta mahsuloti",
    price: 71,
    rating: 3.5,
    discount: 20,
    images: [
      "../assets/images/products/25.png",
      "../assets/images/products/26.png",
      "../assets/images/products/27.png",
      "../assets/images/products/28.png",
    ],
  },
  {
    id: 26,
    name: "Qaymoqda pishirilgan non",
    category: "Nonushta",
    description: "Un, tuxum va sutdan tayyorlanadigan mashhur nonushta taomi",
    price: 63,
    rating: 4,
    discount: 0,
    images: [
      "../assets/images/products/26.png",
      "../assets/images/products/27.png",
      "../assets/images/products/28.png",
      "../assets/images/products/29.png",
    ],
  },
  {
    id: 27,
    name: "Vafel",
    category: "Nonushta",
    description: "Xamirni vafel pechida pishirib tayyorlanadigan nonushta taomi",
    price: 97,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/27.png",
      "../assets/images/products/28.png",
      "../assets/images/products/29.png",
      "../assets/images/products/30.png",
    ],
  },
  {
    id: 28,
    name: "Qovurilgan guruch",
    category: "Tushlik",
    description: "Yog'da qovurilgan guruch va boshqa ingredientlardan tayyorlanadigan taom",
    price: 81,
    rating: 4,
    discount: 20,
    images: [
      "../assets/images/products/28.png",
      "../assets/images/products/29.png",
      "../assets/images/products/30.png",
      "../assets/images/products/31.png",
    ],
  },
  {
    id: 29,
    name: "Spagetti",
    category: "Tushlik",
    description: "Bug'doy unidan tayyorlanadigan uzun makaron, odatda sous bilan birga beriladi",
    price: 96,
    rating: 3,
    discount: 50,
    images: [
      "../assets/images/products/29.png",
      "../assets/images/products/30.png",
      "../assets/images/products/31.png",
      "../assets/images/products/32.png",
    ],
  },
  {
    id: 30,
    name: "Pitsa",
    category: "Tushlik",
    description: "Xamir, sous, pishloq va ustunalardan tayyorlanadigan mashhur taom",
    price: 95,
    rating: 4,
    discount: 0,
    images: [
      "../assets/images/products/30.png",
      "../assets/images/products/31.png",
      "../assets/images/products/32.png",
      "../assets/images/products/33.png",
    ],
  },
  {
    id: 31,
    name: "Grill pishloqli sendvich",
    category: "Tushlik",
    description: "Issiq pishloq va nondan tayyorlanadigan sendvich",
    price: 100,
    rating: 5,
    discount: 50,
    images: [
      "../assets/images/products/31.png",
      "../assets/images/products/32.png",
      "../assets/images/products/33.png",
      "../assets/images/products/34.png",
    ],
  },
  {
    id: 32,
    name: "Biftek",
    category: "Kechki ovqat",
    description: "Mol go'shtining kesimi, odatda grillda yoki tovada pishiriladi",
    price: 63,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/32.png",
      "../assets/images/products/33.png",
      "../assets/images/products/34.png",
      "../assets/images/products/35.png",
    ],
  },
  {
    id: 33,
    name: "Losos balig'i",
    category: "Kechki ovqat",
    description:
      "Grillda yoki pechda pishiriladigan va asosiy taom sifatida beriladigan baliq turi",
    price: 82,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/33.png",
      "../assets/images/products/34.png",
      "../assets/images/products/35.png",
      "../assets/images/products/36.png",
    ],
  },
  {
    id: 34,
    name: "Tovuqli Alfredo",
    category: "Kechki ovqat",
    description: "Tovuq, qaymoqli sous va makarondan tayyorlanadigan taom",
    price: 94,
    rating: 4,
    discount: 20,
    images: [
      "../assets/images/products/34.png",
      "../assets/images/products/35.png",
      "../assets/images/products/36.png",
      "../assets/images/products/1.png",
    ],
  },
  {
    id: 35,
    name: "Lazanya",
    category: "Kechki ovqat",
    description:
      "Qatlamli makaron, sous, pishloq va go'sht yoki sabzavotlardan tayyorlanadigan taom",
    price: 70,
    rating: 1,
    discount: 0,
    images: [
      "../assets/images/products/35.png",
      "../assets/images/products/36.png",
      "../assets/images/products/1.png",
      "../assets/images/products/2.png",
    ],
  },
  {
    id: 36,
    name: "Shokoladli pechene",
    category: "Shirinlik",
    description: "Un, shakar, yog' va shokolad bo'laklaridan tayyorlanadigan pechene",
    price: 98,
    rating: 3.5,
    discount: 0,
    images: [
      "../assets/images/products/36.png",
      "../assets/images/products/1.png",
      "../assets/images/products/2.png",
      "../assets/images/products/3.png",
    ],
  },
];
const reklamaProducts = [
  {
    name: "Оформите карту «Северяночка»",
    paragrapx: "И получайте бонусы при покупке в магазинах и на сайте",
    img: "../images/index/karta.png",
  },
  {
    name: "Покупайте акционные товары",
    paragrapx: "И получайте вдвое больше бонусов",
    img: "../images/index/savat.png",
  },
];
const statiProducts = [
  {
    img: "../images/index/image-6.png",
    date: "05.03.2021",
    name: "Режим использования масок и перчаток на территории магазинов",
    paragrapx:
      'Подробная информация о режимах использования масок и перчаток на территории магазинов "ЛЕНТА". Информация обновляется каждый будний день.',
  },
  {
    img: "../images/index/image-7.png",
    date: "05.03.2021",
    name: "Весеннее настроение для каждой",
    paragrapx:
      "8 Марта – это не просто Международный женский день, это ещё день тюльпанов, приятных сюрпризов и праздничных тёплых пожеланий.",
  },
  {
    img: "../images/index/image-8.png",
    date: "22.02.2020",
    name: "ЗОЖ или ФАСТФУД. А вы на чьей стороне? Голосуем!",
    paragrapx:
      "Голосуйте за любимые категории, выбирайте категорию-победителя в мобильном приложении и получайте кешбэк 10% баллами в апреле!",
  },
];
const katalogData = [
  {
    text: "Молоко, сыр, яйцо",
  },
  {
    text: "Хлеб",
  },
  {
    text: "Фрукты и овощи",
  },
  {
    text: "Фрукты и овощи",
  },
  {
    text: "Молоко, сыр, яйцо",
  },
  {
    text: "Напитки",
  },
  {
    text: "Кондитерские изделия",
  },
  {
    text: "Чай, кофе",
  },
  {
    text: "Бакалея",
  },
  {
    text: "Здоровое питание",
  },
  {
    text: "Здоровое питание",
  },
  {
    text: "Детское питание",
  },
  {
    text: "Мясо, птица, колбаса",
  },
];
const productDataKatalog = [
  {
    id: 1,
    text: "Sut, pishloq, tuxum",
    image: "../images/katalog/image-1.png",
  },
  {
    id: 2,
    text: "Non",
    image: "../images/katalog/image-2.png",
  },
  {
    id: 3,
    text: "Mevalar va sabzavotlar",
    image: "../images/katalog/image-3.png",
  },
  {
    id: 4,
    text: "Mevalar va sabzavotlar",
    image: "../images/katalog/image-4.png",
  },
  {
    id: 5,
    text: "Sut, pishloq, tuxum",
    image: "../images/katalog/image-5.png",
  },
  {
    id: 6,
    text: "Ichimliklar",
    image: "../images/katalog/image-6.png",
  },
  {
    id: 7,
    text: "Qandolat mahsulotlari",
    image: "../images/katalog/image-7.png",
  },
  {
    id: 8,
    text: "Choy, qahva",
    image: "../images/katalog/image-8.png",
  },
  {
    id: 9,
    text: "Bakaleya",
    image: "../images/katalog/image-9.png",
  },
  {
    id: 10,
    text: "Sog‘lom ovqatlanish",
    image: "../images/katalog/image-10.png",
  },
  {
    id: 11,
    text: "Sog‘lom ovqatlanish",
    image: "../images/katalog/image-11.png",
  },
  {
    id: 12,
    text: "Bolalar ovqati",
    image: "../images/katalog/image-12.png",
  },
  {
    id: 13,
    text: "Go‘sht, parranda, kolbasa",
    image: "../images/katalog/image-13.png",
  },
];
